/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UnauthenticatedImport } from './routes/_unauthenticated'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as UnauthenticatedSignupImport } from './routes/_unauthenticated/signup'
import { Route as UnauthenticatedLoginImport } from './routes/_unauthenticated/login'
import { Route as AuthenticatedProfilesImport } from './routes/_authenticated/profiles'
import { Route as AuthenticatedNotificationsImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedSettingsImport } from './routes/_authenticated/_settings'
import { Route as AuthenticatedScheduleImport } from './routes/_authenticated/_schedule'
import { Route as AuthenticatedProfileImport } from './routes/_authenticated/_profile'
import { Route as AuthenticatedPointOfSaleImport } from './routes/_authenticated/_point-of-sale'
import { Route as AuthenticatedSettingsSettingsIndexImport } from './routes/_authenticated/_settings.settings/index'
import { Route as AuthenticatedScheduleScheduleIndexImport } from './routes/_authenticated/_schedule.schedule/index'
import { Route as AuthenticatedPointOfSalePointOfSaleIndexImport } from './routes/_authenticated/_point-of-sale.point-of-sale/index'
import { Route as AuthenticatedSettingsSettingsInventoryImport } from './routes/_authenticated/_settings.settings/inventory'
import { Route as AuthenticatedSettingsSettingsCategoriesImport } from './routes/_authenticated/_settings.settings/categories'
import { Route as AuthenticatedSettingsSettingsAgreementsImport } from './routes/_authenticated/_settings.settings/agreements'
import { Route as AuthenticatedSettingsSettingsActivityImport } from './routes/_authenticated/_settings.settings/activity'
import { Route as AuthenticatedSettingsSettingsAccountsImport } from './routes/_authenticated/_settings.settings/accounts'
import { Route as AuthenticatedPointOfSalePointOfSaleUnpaidInvoicesImport } from './routes/_authenticated/_point-of-sale.point-of-sale/unpaid-invoices'
import { Route as AuthenticatedPointOfSalePointOfSaleOtherImport } from './routes/_authenticated/_point-of-sale.point-of-sale/other'
import { Route as AuthenticatedPointOfSalePointOfSaleAgreementsImport } from './routes/_authenticated/_point-of-sale.point-of-sale/agreements'
import { Route as AuthenticatedPointOfSalePointOfSaleActivitiesImport } from './routes/_authenticated/_point-of-sale.point-of-sale/activities'
import { Route as AuthenticatedProfileProfileProfileIdIndexImport } from './routes/_authenticated/_profile.profile.$profileId/index'
import { Route as AuthenticatedProfileProfileProfileIdNotesImport } from './routes/_authenticated/_profile.profile.$profileId/notes'
import { Route as AuthenticatedProfileProfileProfileIdFinanceImport } from './routes/_authenticated/_profile.profile.$profileId/finance'
import { Route as AuthenticatedProfileProfileProfileIdDetailsImport } from './routes/_authenticated/_profile.profile.$profileId/details'
import { Route as AuthenticatedProfileProfileProfileIdAgreementsImport } from './routes/_authenticated/_profile.profile.$profileId/agreements'
import { Route as AuthenticatedProfileProfileProfileIdActivitiesImport } from './routes/_authenticated/_profile.profile.$profileId/activities'

// Create/Update Routes

const UnauthenticatedRoute = UnauthenticatedImport.update({
  id: '/_unauthenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const UnauthenticatedSignupRoute = UnauthenticatedSignupImport.update({
  path: '/signup',
  getParentRoute: () => UnauthenticatedRoute,
} as any)

const UnauthenticatedLoginRoute = UnauthenticatedLoginImport.update({
  path: '/login',
  getParentRoute: () => UnauthenticatedRoute,
} as any)

const AuthenticatedProfilesRoute = AuthenticatedProfilesImport.update({
  path: '/profiles',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedNotificationsRoute = AuthenticatedNotificationsImport.update(
  {
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any,
)

const AuthenticatedSettingsRoute = AuthenticatedSettingsImport.update({
  id: '/_settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedScheduleRoute = AuthenticatedScheduleImport.update({
  id: '/_schedule',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedProfileRoute = AuthenticatedProfileImport.update({
  id: '/_profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedPointOfSaleRoute = AuthenticatedPointOfSaleImport.update({
  id: '/_point-of-sale',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedSettingsSettingsIndexRoute =
  AuthenticatedSettingsSettingsIndexImport.update({
    path: '/settings/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)

const AuthenticatedScheduleScheduleIndexRoute =
  AuthenticatedScheduleScheduleIndexImport.update({
    path: '/schedule/',
    getParentRoute: () => AuthenticatedScheduleRoute,
  } as any)

const AuthenticatedPointOfSalePointOfSaleIndexRoute =
  AuthenticatedPointOfSalePointOfSaleIndexImport.update({
    path: '/point-of-sale/',
    getParentRoute: () => AuthenticatedPointOfSaleRoute,
  } as any)

const AuthenticatedSettingsSettingsInventoryRoute =
  AuthenticatedSettingsSettingsInventoryImport.update({
    path: '/settings/inventory',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)

const AuthenticatedSettingsSettingsCategoriesRoute =
  AuthenticatedSettingsSettingsCategoriesImport.update({
    path: '/settings/categories',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)

const AuthenticatedSettingsSettingsAgreementsRoute =
  AuthenticatedSettingsSettingsAgreementsImport.update({
    path: '/settings/agreements',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)

const AuthenticatedSettingsSettingsActivityRoute =
  AuthenticatedSettingsSettingsActivityImport.update({
    path: '/settings/activity',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)

const AuthenticatedSettingsSettingsAccountsRoute =
  AuthenticatedSettingsSettingsAccountsImport.update({
    path: '/settings/accounts',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)

const AuthenticatedPointOfSalePointOfSaleUnpaidInvoicesRoute =
  AuthenticatedPointOfSalePointOfSaleUnpaidInvoicesImport.update({
    path: '/point-of-sale/unpaid-invoices',
    getParentRoute: () => AuthenticatedPointOfSaleRoute,
  } as any)

const AuthenticatedPointOfSalePointOfSaleOtherRoute =
  AuthenticatedPointOfSalePointOfSaleOtherImport.update({
    path: '/point-of-sale/other',
    getParentRoute: () => AuthenticatedPointOfSaleRoute,
  } as any)

const AuthenticatedPointOfSalePointOfSaleAgreementsRoute =
  AuthenticatedPointOfSalePointOfSaleAgreementsImport.update({
    path: '/point-of-sale/agreements',
    getParentRoute: () => AuthenticatedPointOfSaleRoute,
  } as any)

const AuthenticatedPointOfSalePointOfSaleActivitiesRoute =
  AuthenticatedPointOfSalePointOfSaleActivitiesImport.update({
    path: '/point-of-sale/activities',
    getParentRoute: () => AuthenticatedPointOfSaleRoute,
  } as any)

const AuthenticatedProfileProfileProfileIdIndexRoute =
  AuthenticatedProfileProfileProfileIdIndexImport.update({
    path: '/profile/$profileId/',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)

const AuthenticatedProfileProfileProfileIdNotesRoute =
  AuthenticatedProfileProfileProfileIdNotesImport.update({
    path: '/profile/$profileId/notes',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)

const AuthenticatedProfileProfileProfileIdFinanceRoute =
  AuthenticatedProfileProfileProfileIdFinanceImport.update({
    path: '/profile/$profileId/finance',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)

const AuthenticatedProfileProfileProfileIdDetailsRoute =
  AuthenticatedProfileProfileProfileIdDetailsImport.update({
    path: '/profile/$profileId/details',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)

const AuthenticatedProfileProfileProfileIdAgreementsRoute =
  AuthenticatedProfileProfileProfileIdAgreementsImport.update({
    path: '/profile/$profileId/agreements',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)

const AuthenticatedProfileProfileProfileIdActivitiesRoute =
  AuthenticatedProfileProfileProfileIdActivitiesImport.update({
    path: '/profile/$profileId/activities',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_unauthenticated': {
      id: '/_unauthenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof UnauthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/_point-of-sale': {
      id: '/_authenticated/_point-of-sale'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedPointOfSaleImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/_profile': {
      id: '/_authenticated/_profile'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedProfileImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/_schedule': {
      id: '/_authenticated/_schedule'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedScheduleImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/_settings': {
      id: '/_authenticated/_settings'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedSettingsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/profiles': {
      id: '/_authenticated/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof AuthenticatedProfilesImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_unauthenticated/login': {
      id: '/_unauthenticated/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof UnauthenticatedLoginImport
      parentRoute: typeof UnauthenticatedImport
    }
    '/_unauthenticated/signup': {
      id: '/_unauthenticated/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof UnauthenticatedSignupImport
      parentRoute: typeof UnauthenticatedImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/_point-of-sale/point-of-sale/activities': {
      id: '/_authenticated/_point-of-sale/point-of-sale/activities'
      path: '/point-of-sale/activities'
      fullPath: '/point-of-sale/activities'
      preLoaderRoute: typeof AuthenticatedPointOfSalePointOfSaleActivitiesImport
      parentRoute: typeof AuthenticatedPointOfSaleImport
    }
    '/_authenticated/_point-of-sale/point-of-sale/agreements': {
      id: '/_authenticated/_point-of-sale/point-of-sale/agreements'
      path: '/point-of-sale/agreements'
      fullPath: '/point-of-sale/agreements'
      preLoaderRoute: typeof AuthenticatedPointOfSalePointOfSaleAgreementsImport
      parentRoute: typeof AuthenticatedPointOfSaleImport
    }
    '/_authenticated/_point-of-sale/point-of-sale/other': {
      id: '/_authenticated/_point-of-sale/point-of-sale/other'
      path: '/point-of-sale/other'
      fullPath: '/point-of-sale/other'
      preLoaderRoute: typeof AuthenticatedPointOfSalePointOfSaleOtherImport
      parentRoute: typeof AuthenticatedPointOfSaleImport
    }
    '/_authenticated/_point-of-sale/point-of-sale/unpaid-invoices': {
      id: '/_authenticated/_point-of-sale/point-of-sale/unpaid-invoices'
      path: '/point-of-sale/unpaid-invoices'
      fullPath: '/point-of-sale/unpaid-invoices'
      preLoaderRoute: typeof AuthenticatedPointOfSalePointOfSaleUnpaidInvoicesImport
      parentRoute: typeof AuthenticatedPointOfSaleImport
    }
    '/_authenticated/_settings/settings/accounts': {
      id: '/_authenticated/_settings/settings/accounts'
      path: '/settings/accounts'
      fullPath: '/settings/accounts'
      preLoaderRoute: typeof AuthenticatedSettingsSettingsAccountsImport
      parentRoute: typeof AuthenticatedSettingsImport
    }
    '/_authenticated/_settings/settings/activity': {
      id: '/_authenticated/_settings/settings/activity'
      path: '/settings/activity'
      fullPath: '/settings/activity'
      preLoaderRoute: typeof AuthenticatedSettingsSettingsActivityImport
      parentRoute: typeof AuthenticatedSettingsImport
    }
    '/_authenticated/_settings/settings/agreements': {
      id: '/_authenticated/_settings/settings/agreements'
      path: '/settings/agreements'
      fullPath: '/settings/agreements'
      preLoaderRoute: typeof AuthenticatedSettingsSettingsAgreementsImport
      parentRoute: typeof AuthenticatedSettingsImport
    }
    '/_authenticated/_settings/settings/categories': {
      id: '/_authenticated/_settings/settings/categories'
      path: '/settings/categories'
      fullPath: '/settings/categories'
      preLoaderRoute: typeof AuthenticatedSettingsSettingsCategoriesImport
      parentRoute: typeof AuthenticatedSettingsImport
    }
    '/_authenticated/_settings/settings/inventory': {
      id: '/_authenticated/_settings/settings/inventory'
      path: '/settings/inventory'
      fullPath: '/settings/inventory'
      preLoaderRoute: typeof AuthenticatedSettingsSettingsInventoryImport
      parentRoute: typeof AuthenticatedSettingsImport
    }
    '/_authenticated/_point-of-sale/point-of-sale/': {
      id: '/_authenticated/_point-of-sale/point-of-sale/'
      path: '/point-of-sale'
      fullPath: '/point-of-sale'
      preLoaderRoute: typeof AuthenticatedPointOfSalePointOfSaleIndexImport
      parentRoute: typeof AuthenticatedPointOfSaleImport
    }
    '/_authenticated/_schedule/schedule/': {
      id: '/_authenticated/_schedule/schedule/'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthenticatedScheduleScheduleIndexImport
      parentRoute: typeof AuthenticatedScheduleImport
    }
    '/_authenticated/_settings/settings/': {
      id: '/_authenticated/_settings/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsSettingsIndexImport
      parentRoute: typeof AuthenticatedSettingsImport
    }
    '/_authenticated/_profile/profile/$profileId/activities': {
      id: '/_authenticated/_profile/profile/$profileId/activities'
      path: '/profile/$profileId/activities'
      fullPath: '/profile/$profileId/activities'
      preLoaderRoute: typeof AuthenticatedProfileProfileProfileIdActivitiesImport
      parentRoute: typeof AuthenticatedProfileImport
    }
    '/_authenticated/_profile/profile/$profileId/agreements': {
      id: '/_authenticated/_profile/profile/$profileId/agreements'
      path: '/profile/$profileId/agreements'
      fullPath: '/profile/$profileId/agreements'
      preLoaderRoute: typeof AuthenticatedProfileProfileProfileIdAgreementsImport
      parentRoute: typeof AuthenticatedProfileImport
    }
    '/_authenticated/_profile/profile/$profileId/details': {
      id: '/_authenticated/_profile/profile/$profileId/details'
      path: '/profile/$profileId/details'
      fullPath: '/profile/$profileId/details'
      preLoaderRoute: typeof AuthenticatedProfileProfileProfileIdDetailsImport
      parentRoute: typeof AuthenticatedProfileImport
    }
    '/_authenticated/_profile/profile/$profileId/finance': {
      id: '/_authenticated/_profile/profile/$profileId/finance'
      path: '/profile/$profileId/finance'
      fullPath: '/profile/$profileId/finance'
      preLoaderRoute: typeof AuthenticatedProfileProfileProfileIdFinanceImport
      parentRoute: typeof AuthenticatedProfileImport
    }
    '/_authenticated/_profile/profile/$profileId/notes': {
      id: '/_authenticated/_profile/profile/$profileId/notes'
      path: '/profile/$profileId/notes'
      fullPath: '/profile/$profileId/notes'
      preLoaderRoute: typeof AuthenticatedProfileProfileProfileIdNotesImport
      parentRoute: typeof AuthenticatedProfileImport
    }
    '/_authenticated/_profile/profile/$profileId/': {
      id: '/_authenticated/_profile/profile/$profileId/'
      path: '/profile/$profileId'
      fullPath: '/profile/$profileId'
      preLoaderRoute: typeof AuthenticatedProfileProfileProfileIdIndexImport
      parentRoute: typeof AuthenticatedProfileImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  AuthenticatedRoute: AuthenticatedRoute.addChildren({
    AuthenticatedPointOfSaleRoute: AuthenticatedPointOfSaleRoute.addChildren({
      AuthenticatedPointOfSalePointOfSaleActivitiesRoute,
      AuthenticatedPointOfSalePointOfSaleAgreementsRoute,
      AuthenticatedPointOfSalePointOfSaleOtherRoute,
      AuthenticatedPointOfSalePointOfSaleUnpaidInvoicesRoute,
      AuthenticatedPointOfSalePointOfSaleIndexRoute,
    }),
    AuthenticatedProfileRoute: AuthenticatedProfileRoute.addChildren({
      AuthenticatedProfileProfileProfileIdActivitiesRoute,
      AuthenticatedProfileProfileProfileIdAgreementsRoute,
      AuthenticatedProfileProfileProfileIdDetailsRoute,
      AuthenticatedProfileProfileProfileIdFinanceRoute,
      AuthenticatedProfileProfileProfileIdNotesRoute,
      AuthenticatedProfileProfileProfileIdIndexRoute,
    }),
    AuthenticatedScheduleRoute: AuthenticatedScheduleRoute.addChildren({
      AuthenticatedScheduleScheduleIndexRoute,
    }),
    AuthenticatedSettingsRoute: AuthenticatedSettingsRoute.addChildren({
      AuthenticatedSettingsSettingsAccountsRoute,
      AuthenticatedSettingsSettingsActivityRoute,
      AuthenticatedSettingsSettingsAgreementsRoute,
      AuthenticatedSettingsSettingsCategoriesRoute,
      AuthenticatedSettingsSettingsInventoryRoute,
      AuthenticatedSettingsSettingsIndexRoute,
    }),
    AuthenticatedNotificationsRoute,
    AuthenticatedProfilesRoute,
    AuthenticatedIndexRoute,
  }),
  UnauthenticatedRoute: UnauthenticatedRoute.addChildren({
    UnauthenticatedLoginRoute,
    UnauthenticatedSignupRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/_unauthenticated"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/_point-of-sale",
        "/_authenticated/_profile",
        "/_authenticated/_schedule",
        "/_authenticated/_settings",
        "/_authenticated/notifications",
        "/_authenticated/profiles",
        "/_authenticated/"
      ]
    },
    "/_unauthenticated": {
      "filePath": "_unauthenticated.tsx",
      "children": [
        "/_unauthenticated/login",
        "/_unauthenticated/signup"
      ]
    },
    "/_authenticated/_point-of-sale": {
      "filePath": "_authenticated/_point-of-sale.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/_point-of-sale/point-of-sale/activities",
        "/_authenticated/_point-of-sale/point-of-sale/agreements",
        "/_authenticated/_point-of-sale/point-of-sale/other",
        "/_authenticated/_point-of-sale/point-of-sale/unpaid-invoices",
        "/_authenticated/_point-of-sale/point-of-sale/"
      ]
    },
    "/_authenticated/_profile": {
      "filePath": "_authenticated/_profile.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/_profile/profile/$profileId/activities",
        "/_authenticated/_profile/profile/$profileId/agreements",
        "/_authenticated/_profile/profile/$profileId/details",
        "/_authenticated/_profile/profile/$profileId/finance",
        "/_authenticated/_profile/profile/$profileId/notes",
        "/_authenticated/_profile/profile/$profileId/"
      ]
    },
    "/_authenticated/_schedule": {
      "filePath": "_authenticated/_schedule.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/_schedule/schedule/"
      ]
    },
    "/_authenticated/_settings": {
      "filePath": "_authenticated/_settings.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/_settings/settings/accounts",
        "/_authenticated/_settings/settings/activity",
        "/_authenticated/_settings/settings/agreements",
        "/_authenticated/_settings/settings/categories",
        "/_authenticated/_settings/settings/inventory",
        "/_authenticated/_settings/settings/"
      ]
    },
    "/_authenticated/notifications": {
      "filePath": "_authenticated/notifications.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/profiles": {
      "filePath": "_authenticated/profiles.tsx",
      "parent": "/_authenticated"
    },
    "/_unauthenticated/login": {
      "filePath": "_unauthenticated/login.tsx",
      "parent": "/_unauthenticated"
    },
    "/_unauthenticated/signup": {
      "filePath": "_unauthenticated/signup.tsx",
      "parent": "/_unauthenticated"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/_point-of-sale/point-of-sale/activities": {
      "filePath": "_authenticated/_point-of-sale.point-of-sale/activities.tsx",
      "parent": "/_authenticated/_point-of-sale"
    },
    "/_authenticated/_point-of-sale/point-of-sale/agreements": {
      "filePath": "_authenticated/_point-of-sale.point-of-sale/agreements.tsx",
      "parent": "/_authenticated/_point-of-sale"
    },
    "/_authenticated/_point-of-sale/point-of-sale/other": {
      "filePath": "_authenticated/_point-of-sale.point-of-sale/other.tsx",
      "parent": "/_authenticated/_point-of-sale"
    },
    "/_authenticated/_point-of-sale/point-of-sale/unpaid-invoices": {
      "filePath": "_authenticated/_point-of-sale.point-of-sale/unpaid-invoices.tsx",
      "parent": "/_authenticated/_point-of-sale"
    },
    "/_authenticated/_settings/settings/accounts": {
      "filePath": "_authenticated/_settings.settings/accounts.tsx",
      "parent": "/_authenticated/_settings"
    },
    "/_authenticated/_settings/settings/activity": {
      "filePath": "_authenticated/_settings.settings/activity.tsx",
      "parent": "/_authenticated/_settings"
    },
    "/_authenticated/_settings/settings/agreements": {
      "filePath": "_authenticated/_settings.settings/agreements.tsx",
      "parent": "/_authenticated/_settings"
    },
    "/_authenticated/_settings/settings/categories": {
      "filePath": "_authenticated/_settings.settings/categories.tsx",
      "parent": "/_authenticated/_settings"
    },
    "/_authenticated/_settings/settings/inventory": {
      "filePath": "_authenticated/_settings.settings/inventory.tsx",
      "parent": "/_authenticated/_settings"
    },
    "/_authenticated/_point-of-sale/point-of-sale/": {
      "filePath": "_authenticated/_point-of-sale.point-of-sale/index.tsx",
      "parent": "/_authenticated/_point-of-sale"
    },
    "/_authenticated/_schedule/schedule/": {
      "filePath": "_authenticated/_schedule.schedule/index.tsx",
      "parent": "/_authenticated/_schedule"
    },
    "/_authenticated/_settings/settings/": {
      "filePath": "_authenticated/_settings.settings/index.tsx",
      "parent": "/_authenticated/_settings"
    },
    "/_authenticated/_profile/profile/$profileId/activities": {
      "filePath": "_authenticated/_profile.profile.$profileId/activities.tsx",
      "parent": "/_authenticated/_profile"
    },
    "/_authenticated/_profile/profile/$profileId/agreements": {
      "filePath": "_authenticated/_profile.profile.$profileId/agreements.tsx",
      "parent": "/_authenticated/_profile"
    },
    "/_authenticated/_profile/profile/$profileId/details": {
      "filePath": "_authenticated/_profile.profile.$profileId/details.tsx",
      "parent": "/_authenticated/_profile"
    },
    "/_authenticated/_profile/profile/$profileId/finance": {
      "filePath": "_authenticated/_profile.profile.$profileId/finance.tsx",
      "parent": "/_authenticated/_profile"
    },
    "/_authenticated/_profile/profile/$profileId/notes": {
      "filePath": "_authenticated/_profile.profile.$profileId/notes.tsx",
      "parent": "/_authenticated/_profile"
    },
    "/_authenticated/_profile/profile/$profileId/": {
      "filePath": "_authenticated/_profile.profile.$profileId/index.tsx",
      "parent": "/_authenticated/_profile"
    }
  }
}
ROUTE_MANIFEST_END */
